export const INC_COUNTER="INC_COUNTER";
export const DEC_COUNTER="DEC_COUNTER";
export const ADD_COUNTER="ADD_COUNTER";
export const SUB_COUNTER="SUB_COUNTER";
export const MULTi_COUNTER="MULTI_COUNTER";
export const DIVION_COUNTER="DIVION_COUNTER";

export const AUTH_SuCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";