export const GET_DATA = 'GET_DATA';
export const POST_DATA = 'POST_DATA';

//Get One User Data
export const GET_ONE_USER_COMMENT_REQUESTED = 'GET_ONE_USER_COMMENT_REQUESTED';
export const GET_ONE_USER_COMMENT_SUCCESS = 'GET_ONE_USER_COMMENT_SUCCESS';
export const GET_ONE_USER_COMMENT_FAILED = 'GET_ONE_USER_COMMENT_FAILED';

//Get Total User Data
export const GET__TOTAL_USERS_REQUESTED = 'GET__TOTAL_USERS_REQUESTED';
export const GET__TOTAL_USERS_SUCCESS = 'GET__TOTAL_USERS_SUCCESS';
export const GET__TOTAL_USERS_FAILED = 'GET__TOTAL_USERS_FAILED';

//Post Data
export const POST_DATA_REQUESTED = 'POST_DATA_REQUESTED';
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';
export const POST_DATA_FAILED = 'POST_DATA_FAILED';


//Display methods

export const SHOW_ALL_USERS = 'SHOW_ALL_USERS';
export const SHOW_ONE_USER_COMMENT = 'SHOW_ONE_USER_COMMENT';
export const SHOW_POST_DATA = 'SHOW_POST_DATA';

