
export const CREATE_POST_DEPARTMENT_START = 'CREATE_POST_DEPARTMENT_START';
export const CREATE_POST_DEPARTMENT_SUCCESS = 'CREATE_POST_DEPARTMENT_SUCCESS';
export const CREATE_POST_DEPARTMENT_ERROR = 'CREATE_POST_DEPARTMENT_ERROR';

//HOME SETTINGS
export const DEPARTMENT ="DEPARTMENT";
export const DEPARTMENT_HEAD ="DEPARTMENT_HEAD";
export const EMPLOYEE = "EMPLOYEE";

//GET DEPARTMENT

export const GET_DEPARTMENT_START ='GET_DEPARTMENT_START';
export const GET_DEPARTMENT_SUCCESS ='GET_DEPARTMENT_SUCCESS';
export const GET_DEPARTMENT_ERROR ='GET_DEPARTMENT_ERROR';

//EDIT DEPARTMEMNT

export const GET_EDIT_DEPARTMENT_START ='GET_EDIT_DEPARTMENT_SUCCESS';
export const GET_EDIT_DEPARTMENT_ERROR ='GET_EDIT_DEPARTMENT_ERROR';
export const GET_EDIT_DEPARTMENT_SUCCESS ='GET_EDIT_DEPARTMENT_SUCCESS';


export const TOTAL ="TOTAL"