//fetch the all data from json-server
export const LOAD_USERS_START = 'LOAD_USER_START';
export const LOAD_USERS_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USERS_ERROR = 'LOAD_USER_ERROR';

export const CREATE_USER_START = 'LOAD_CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'LOAD_CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'LOAD_CREATE_USER_ERROR';

export const DELETE_USER_START = 'LOAD_DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'LOAD_DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'LOAD_DELETE_USER_ERROR';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
